package scaffold

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
	"time"
)

func TestGenerateResourceWritesMigrationQueriesAndHandler(t *testing.T) {
	destination := filepath.Join(t.TempDir(), "journal")
	if err := GenerateApp(App{
		Destination: destination,
		Module:      "example.com/journal",
		Database:    DatabaseSQLite,
		OhmVersion:  "v0.0.0",
	}); err != nil {
		t.Fatalf("GenerateApp(journal) error = %v, want nil", err)
	}

	result, err := GenerateResource(Resource{
		Name: "Posts",
		Fields: []ResourceField{
			{Name: "title", Type: "string"},
			{Name: "body", Type: "text"},
		},
		Dir: destination,
		Now: func() time.Time {
			return time.Date(2026, 6, 1, 2, 3, 4, 0, time.FixedZone("test", -4*60*60))
		},
	})
	if err != nil {
		t.Fatalf("GenerateResource(Posts) error = %v, want nil", err)
	}

	migrationPath := filepath.Join(destination, "migrations", "20260601060304_create_posts.sql")
	queryPath := filepath.Join(destination, "queries", "posts.sql")
	handlersDir := filepath.Join(destination, "internal", "handlers")
	wantCreated := []string{
		migrationPath,
		queryPath,
		filepath.Join(handlersDir, "posts.go"),
		filepath.Join(handlersDir, "posts_test.go"),
	}
	if !slices.Equal(result.CreatedFiles, wantCreated) {
		t.Errorf("GenerateResource(Posts) created files = %v, want %v", result.CreatedFiles, wantCreated)
	}
	if result.RegisterFile != filepath.Join(handlersDir, "routes.go") {
		t.Errorf("GenerateResource(Posts) register file = %q, want %q", result.RegisterFile, filepath.Join(handlersDir, "routes.go"))
	}
	if !result.RegisterUpdated {
		t.Errorf("GenerateResource(Posts) register updated = false, want true")
	}
	if result.RoutePath != "/posts" {
		t.Errorf("GenerateResource(Posts) route path = %q, want %q", result.RoutePath, "/posts")
	}

	migration := readFile(t, migrationPath)
	for _, want := range []string{
		`CREATE TABLE "posts"`,
		`"id" INTEGER PRIMARY KEY AUTOINCREMENT`,
		`"title" TEXT NOT NULL`,
		`"body" TEXT NOT NULL`,
		`DROP TABLE "posts";`,
	} {
		if !strings.Contains(migration, want) {
			t.Errorf("GenerateResource(Posts) migration = %q, want %q", migration, want)
		}
	}

	queries := readFile(t, queryPath)
	for _, want := range []string{
		`-- name: ListPosts :many`,
		`-- name: GetPosts :one`,
		`-- name: CreatePosts :one`,
		`-- name: UpdatePosts :one`,
		`-- name: DeletePosts :exec`,
		`VALUES (?1, ?2)`,
		`WHERE "id" = ?1`,
	} {
		if !strings.Contains(queries, want) {
			t.Errorf("GenerateResource(Posts) queries = %q, want %q", queries, want)
		}
	}

	routes := readFile(t, filepath.Join(handlersDir, "routes.go"))
	if !strings.Contains(routes, `application.Get("/posts", PostsIndex)`) {
		t.Errorf("GenerateResource(Posts) routes.go = %q, want posts route registration", routes)
	}

	root := repoRoot(t)
	runGo(t, destination, "mod", "edit", "-replace", "github.com/mgomes/ohm="+root)
	runGo(t, destination, "mod", "tidy")
	runGo(t, destination, "run", "github.com/sqlc-dev/sqlc/cmd/sqlc@v1.30.0", "generate")
	runGo(t, destination, "test", "./...")
}

func TestGenerateResourceUsesPostgresSQL(t *testing.T) {
	destination := filepath.Join(t.TempDir(), "ledger")
	if err := GenerateApp(App{
		Destination: destination,
		Module:      "example.com/ledger",
		Database:    DatabasePostgres,
		OhmVersion:  "v0.0.0",
	}); err != nil {
		t.Fatalf("GenerateApp(ledger) error = %v, want nil", err)
	}

	_, err := GenerateResource(Resource{
		Name: "Posts",
		Fields: []ResourceField{
			{Name: "title", Type: "string"},
			{Name: "body", Type: "text"},
		},
		Dir: destination,
		Now: func() time.Time {
			return time.Date(2026, 6, 1, 2, 3, 4, 0, time.UTC)
		},
	})
	if err != nil {
		t.Fatalf("GenerateResource(Posts) error = %v, want nil", err)
	}

	migration := readFile(t, filepath.Join(destination, "migrations", "20260601020304_create_posts.sql"))
	if !strings.Contains(migration, `"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`) {
		t.Errorf("GenerateResource(Posts) Postgres migration = %q, want identity primary key", migration)
	}

	queries := readFile(t, filepath.Join(destination, "queries", "posts.sql"))
	for _, want := range []string{
		`VALUES ($1, $2)`,
		`WHERE "id" = $1`,
		`"title" = $2`,
		`"body" = $3`,
	} {
		if !strings.Contains(queries, want) {
			t.Errorf("GenerateResource(Posts) Postgres queries = %q, want %q", queries, want)
		}
	}
}

func TestGenerateResourceDoesNotWritePartialFilesWhenQueryExists(t *testing.T) {
	destination := filepath.Join(t.TempDir(), "journal")
	if err := GenerateApp(App{
		Destination: destination,
		Module:      "example.com/journal",
		Database:    DatabaseSQLite,
		OhmVersion:  "v0.0.0",
	}); err != nil {
		t.Fatalf("GenerateApp(journal) error = %v, want nil", err)
	}

	queryPath := filepath.Join(destination, "queries", "posts.sql")
	if err := os.WriteFile(queryPath, []byte("keep\n"), 0o644); err != nil {
		t.Fatalf("os.WriteFile(existing query) error = %v, want nil", err)
	}

	_, err := GenerateResource(Resource{
		Name: "Posts",
		Fields: []ResourceField{
			{Name: "title", Type: "string"},
		},
		Dir: destination,
		Now: func() time.Time {
			return time.Date(2026, 6, 1, 2, 3, 4, 0, time.UTC)
		},
	})
	if err == nil {
		t.Fatalf("GenerateResource(existing query) error = nil, want non-nil")
	}
	if got := readFile(t, queryPath); got != "keep\n" {
		t.Errorf("GenerateResource(existing query) query = %q, want %q", got, "keep\n")
	}

	handlersDir := filepath.Join(destination, "internal", "handlers")
	if _, statErr := os.Stat(filepath.Join(handlersDir, "posts.go")); !os.IsNotExist(statErr) {
		t.Errorf("GenerateResource(existing query) posts.go stat error = %v, want not exist", statErr)
	}
	routes := readFile(t, filepath.Join(handlersDir, "routes.go"))
	if strings.Contains(routes, `application.Get("/posts", PostsIndex)`) {
		t.Errorf("GenerateResource(existing query) routes.go = %q, want no posts route registration", routes)
	}
	migrations, err := filepath.Glob(filepath.Join(destination, "migrations", "*_create_posts.sql"))
	if err != nil {
		t.Fatalf("filepath.Glob(resource migrations) error = %v, want nil", err)
	}
	if len(migrations) != 0 {
		t.Errorf("GenerateResource(existing query) migrations = %v, want none", migrations)
	}
}

func TestGenerateResourceRejectsUnsupportedFieldTypes(t *testing.T) {
	destination := filepath.Join(t.TempDir(), "journal")
	if err := GenerateApp(App{
		Destination: destination,
		Module:      "example.com/journal",
		Database:    DatabaseSQLite,
		OhmVersion:  "v0.0.0",
	}); err != nil {
		t.Fatalf("GenerateApp(journal) error = %v, want nil", err)
	}

	_, err := GenerateResource(Resource{
		Name: "Posts",
		Fields: []ResourceField{
			{Name: "published", Type: "bool"},
		},
		Dir: destination,
	})
	if err == nil {
		t.Fatalf("GenerateResource(unsupported field) error = nil, want non-nil")
	}
	if !strings.Contains(err.Error(), "unsupported type") {
		t.Errorf("GenerateResource(unsupported field) error = %v, want unsupported type context", err)
	}
}

func TestGenerateResourceRejectsDuplicateOrReservedFields(t *testing.T) {
	destination := filepath.Join(t.TempDir(), "journal")
	if err := GenerateApp(App{
		Destination: destination,
		Module:      "example.com/journal",
		Database:    DatabaseSQLite,
		OhmVersion:  "v0.0.0",
	}); err != nil {
		t.Fatalf("GenerateApp(journal) error = %v, want nil", err)
	}

	for _, fields := range [][]ResourceField{
		{{Name: "title", Type: "string"}, {Name: "title", Type: "text"}},
		{{Name: "id", Type: "string"}},
	} {
		_, err := GenerateResource(Resource{Name: "Posts", Fields: fields, Dir: destination})
		if err == nil {
			t.Fatalf("GenerateResource(%v) error = nil, want non-nil", fields)
		}
	}
}
