package scaffold

var viewTemplates = map[string]string{
	"internal/views/layouts/application.templ": `package layouts

templ Application(title string) {
	<!doctype html>
	<html lang="en">
		<head>
			<meta charset="utf-8"/>
			<meta name="viewport" content="width=device-width, initial-scale=1"/>
			<title>{ title }</title>
		</head>
		<body>
			<main>
				{ children... }
			</main>
		</body>
	</html>
}
`,
	"internal/views/layouts/application_templ.go": `// Code generated by templ - DO NOT EDIT.

// templ: version: {{.TemplVersion}}
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Application(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: ` + "`internal/views/layouts/application.templ`" + `, Line: 9, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title></head><body><main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
`,
	"internal/views/pages/error.templ": `package pages

import (
	"strconv"

	"{{.Module}}/internal/views/layouts"
)

templ Error(status int, message string) {
	@layouts.Application(message) {
		<h1>{ message }</h1>
		<p>{ "HTTP " + strconv.Itoa(status) }</p>
	}
}
`,
	"internal/views/pages/error_test.go": `package pages

import (
	"context"
	"strings"
	"testing"
)

func TestErrorRendersApplicationLayout(t *testing.T) {
	var body strings.Builder
	if err := Error(404, "Not Found").Render(context.Background(), &body); err != nil {
		t.Fatalf("Error(status, message).Render(ctx, w) error = %v, want nil", err)
	}
	if !strings.Contains(body.String(), "<title>Not Found</title>") {
		t.Errorf("Error(status, message) body = %q, want page title", body.String())
	}
	if !strings.Contains(body.String(), "<h1>Not Found</h1>") {
		t.Errorf("Error(status, message) body = %q, want heading", body.String())
	}
	if !strings.Contains(body.String(), "<p>HTTP 404</p>") {
		t.Errorf("Error(status, message) body = %q, want status code", body.String())
	}
}
`,
	"internal/views/pages/error_templ.go": `// Code generated by templ - DO NOT EDIT.

// templ: version: {{.TemplVersion}}
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strconv"

	"{{.Module}}/internal/views/layouts"
)

func Error(status int, message string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(message)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: ` + "`internal/views/pages/error.templ`" + `, Line: 11, Col: 15}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h1><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("HTTP " + strconv.Itoa(status))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: ` + "`internal/views/pages/error.templ`" + `, Line: 12, Col: 37}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Application(message).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
`,
	"internal/views/pages/home.templ": `package pages

import (
	"{{.Module}}/internal/views/layouts"
	"{{.Module}}/internal/views/partials"
)

templ Home(title string) {
	@layouts.Application(title) {
		@partials.Home(title)
	}
}
`,
	"internal/views/pages/home_test.go": `package pages

import (
	"context"
	"strings"
	"testing"
)

func TestHomeRendersApplicationLayout(t *testing.T) {
	var body strings.Builder
	if err := Home("{{.Title}}").Render(context.Background(), &body); err != nil {
		t.Fatalf("Home(title).Render(ctx, w) error = %v, want nil", err)
	}
	if !strings.Contains(body.String(), "<title>{{.Title}}</title>") {
		t.Errorf("Home(title) body = %q, want page title", body.String())
	}
	if !strings.Contains(body.String(), "<h1>Welcome to {{.Title}}</h1>") {
		t.Errorf("Home(title) body = %q, want heading", body.String())
	}
	if !strings.Contains(body.String(), ` + "`<section id=\"home\">`" + `) {
		t.Errorf("Home(title) body = %q, want home partial target", body.String())
	}
}
`,
	"internal/views/pages/home_templ.go": `// Code generated by templ - DO NOT EDIT.

// templ: version: {{.TemplVersion}}
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"{{.Module}}/internal/views/layouts"
	"{{.Module}}/internal/views/partials"
)

func Home(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = partials.Home(title).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Application(title).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
`,
	"internal/views/partials/README.md": `# Partials

Place route-addressable templ fragments here.
`,
	"internal/views/partials/home.templ": `package partials

templ Home(title string) {
	<section id="home">
		<h1>{ "Welcome to " + title }</h1>
	</section>
}
`,
	"internal/views/partials/home_test.go": `package partials

import (
	"context"
	"strings"
	"testing"
)

func TestHomeRendersFragmentTarget(t *testing.T) {
	var body strings.Builder
	if err := Home("{{.Title}}").Render(context.Background(), &body); err != nil {
		t.Fatalf("Home(title).Render(ctx, w) error = %v, want nil", err)
	}
	if !strings.Contains(body.String(), ` + "`<section id=\"home\">`" + `) {
		t.Errorf("Home(title) body = %q, want home target", body.String())
	}
	if !strings.Contains(body.String(), "<h1>Welcome to {{.Title}}</h1>") {
		t.Errorf("Home(title) body = %q, want heading", body.String())
	}
	if strings.Contains(body.String(), "<!doctype html>") {
		t.Errorf("Home(title) body = %q, want fragment without document layout", body.String())
	}
}
`,
	"internal/views/partials/home_templ.go": `// Code generated by templ - DO NOT EDIT.

// templ: version: {{.TemplVersion}}
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"home\"><h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var1 string
		templ_7745c5c3_Var1, templ_7745c5c3_Err = templ.JoinStringErrs("Welcome to " + title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: ` + "`internal/views/partials/home.templ`" + `, Line: 5, Col: 29}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var1))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h1></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
`,
	"internal/views/components/README.md": `# Components

Place reusable templ components here.
`,
	"internal/views/components/flash.go": `package components

type FlashLevel string

const (
	FlashInfo    FlashLevel = "info"
	FlashSuccess FlashLevel = "success"
	FlashWarning FlashLevel = "warning"
	FlashError   FlashLevel = "error"
)

type FlashMessage struct {
	Level FlashLevel
	Text  string
}

func NewFlashMessage(level FlashLevel, text string) FlashMessage {
	if level == "" {
		level = FlashInfo
	}
	return FlashMessage{Level: level, Text: text}
}

func (m FlashMessage) CSSClass() string {
	switch m.Level {
	case FlashSuccess:
		return "flash flash-success"
	case FlashWarning:
		return "flash flash-warning"
	case FlashError:
		return "flash flash-error"
	default:
		return "flash flash-info"
	}
}

func (m FlashMessage) Role() string {
	if m.Level == FlashError {
		return "alert"
	}
	return "status"
}
`,
	"internal/views/components/flash.templ": `package components

templ Flash(messages []FlashMessage) {
	if len(messages) > 0 {
		<section aria-label="Notifications" class="flash-messages">
			for _, message := range messages {
				<p class={ message.CSSClass() } role={ message.Role() }>{ message.Text }</p>
			}
		</section>
	}
}
`,
	"internal/views/components/flash_test.go": `package components

import (
	"context"
	"strings"
	"testing"
)

func TestFlashRendersMessages(t *testing.T) {
	messages := []FlashMessage{
		NewFlashMessage(FlashSuccess, "Saved"),
		NewFlashMessage(FlashError, "<failed>"),
	}

	var body strings.Builder
	if err := Flash(messages).Render(context.Background(), &body); err != nil {
		t.Fatalf("Flash(messages).Render(ctx, w) error = %v, want nil", err)
	}
	if !strings.Contains(body.String(), "<section aria-label=\"Notifications\" class=\"flash-messages\">") {
		t.Errorf("Flash(messages) body = %q, want notifications region", body.String())
	}
	if !strings.Contains(body.String(), "<p class=\"flash flash-success\" role=\"status\">Saved</p>") {
		t.Errorf("Flash(messages) body = %q, want success message", body.String())
	}
	if !strings.Contains(body.String(), "<p class=\"flash flash-error\" role=\"alert\">&lt;failed&gt;</p>") {
		t.Errorf("Flash(messages) body = %q, want escaped error alert", body.String())
	}
}

func TestFlashOmitsEmptyMessages(t *testing.T) {
	var body strings.Builder
	if err := Flash(nil).Render(context.Background(), &body); err != nil {
		t.Fatalf("Flash(nil).Render(ctx, w) error = %v, want nil", err)
	}
	if body.String() != "" {
		t.Errorf("Flash(nil) body = %q, want empty", body.String())
	}
}

func TestNewFlashMessageDefaultsLevel(t *testing.T) {
	message := NewFlashMessage("", "Saved")

	if message.Level != FlashInfo {
		t.Errorf("NewFlashMessage(%q, %q).Level = %q, want %q", "", "Saved", message.Level, FlashInfo)
	}
	if message.CSSClass() != "flash flash-info" {
		t.Errorf("NewFlashMessage(%q, %q).CSSClass() = %q, want %q", "", "Saved", message.CSSClass(), "flash flash-info")
	}
	if message.Role() != "status" {
		t.Errorf("NewFlashMessage(%q, %q).Role() = %q, want %q", "", "Saved", message.Role(), "status")
	}
}
`,
	"internal/views/components/flash_templ.go": `// Code generated by templ - DO NOT EDIT.

// templ: version: {{.TemplVersion}}
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Flash(messages []FlashMessage) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if len(messages) > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section aria-label=\"Notifications\" class=\"flash-messages\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, message := range messages {
				var templ_7745c5c3_Var2 = []any{message.CSSClass()}
				templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p class=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var2).String())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: ` + "`internal/views/components/flash.templ`" + `, Line: 1, Col: 0}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" role=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(message.Role())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: ` + "`internal/views/components/flash.templ`" + `, Line: 7, Col: 57}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(message.Text)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: ` + "`internal/views/components/flash.templ`" + `, Line: 7, Col: 74}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
`,
	"internal/views/forms/forms.go": `package forms

import (
	"slices"
	"strings"
	"unicode"
)

type Values map[string]string

type Errors map[string][]string

type Field struct {
	Name   string
	ID     string
	Label  string
	Value  string
	Errors []string
}

func NewField(name string, label string, values Values, errors Errors) Field {
	if label == "" {
		label = Label(name)
	}
	return Field{
		Name:   name,
		ID:     FieldID(name),
		Label:  label,
		Value:  values.Get(name),
		Errors: errors.Get(name),
	}
}

func (v Values) Get(name string) string {
	if v == nil {
		return ""
	}
	return v[name]
}

func (e Errors) Get(name string) []string {
	if e == nil {
		return nil
	}
	return slices.Clone(e[name])
}

func FieldID(name string) string {
	id := normalizedFieldID(name)
	if id == "" {
		return "field"
	}
	return id
}

func Label(name string) string {
	id := normalizedFieldID(name)
	if id == "" {
		return ""
	}

	parts := strings.Split(id, "-")
	for i, part := range parts {
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}
		runes[0] = unicode.ToUpper(runes[0])
		parts[i] = string(runes)
	}
	return strings.Join(parts, " ")
}

func normalizedFieldID(name string) string {
	var builder strings.Builder
	lastSeparator := false
	for _, r := range strings.TrimSpace(name) {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			builder.WriteRune(unicode.ToLower(r))
			lastSeparator = false
			continue
		}
		if builder.Len() > 0 && !lastSeparator {
			builder.WriteByte('-')
			lastSeparator = true
		}
	}

	return strings.Trim(builder.String(), "-")
}
`,
	"internal/views/forms/forms_test.go": `package forms

import (
	"slices"
	"testing"
)

func TestNewFieldBuildsViewData(t *testing.T) {
	values := Values{"post[title]": "Hello"}
	errors := Errors{"post[title]": []string{"is required"}}

	field := NewField("post[title]", "", values, errors)

	if field.Name != "post[title]" {
		t.Errorf("NewField(%q, label, values, errors).Name = %q, want %q", "post[title]", field.Name, "post[title]")
	}
	if field.ID != "post-title" {
		t.Errorf("NewField(%q, label, values, errors).ID = %q, want %q", "post[title]", field.ID, "post-title")
	}
	if field.Label != "Post Title" {
		t.Errorf("NewField(%q, label, values, errors).Label = %q, want %q", "post[title]", field.Label, "Post Title")
	}
	if field.Value != "Hello" {
		t.Errorf("NewField(%q, label, values, errors).Value = %q, want %q", "post[title]", field.Value, "Hello")
	}
	if !slices.Equal(field.Errors, []string{"is required"}) {
		t.Errorf("NewField(%q, label, values, errors).Errors = %v, want %v", "post[title]", field.Errors, []string{"is required"})
	}

	errors["post[title]"][0] = "changed"
	if !slices.Equal(field.Errors, []string{"is required"}) {
		t.Errorf("NewField(%q, label, values, errors).Errors after source mutation = %v, want %v", "post[title]", field.Errors, []string{"is required"})
	}
}

func TestNewFieldUsesExplicitLabel(t *testing.T) {
	field := NewField("email", "Email address", nil, nil)

	if field.Label != "Email address" {
		t.Errorf("NewField(%q, %q, nil, nil).Label = %q, want %q", "email", "Email address", field.Label, "Email address")
	}
}

func TestLabel(t *testing.T) {
	tests := []struct {
		name string
		want string
	}{
		{name: "field", want: "Field"},
		{name: "Field", want: "Field"},
		{name: "post[title]", want: "Post Title"},
		{name: "!!!", want: ""},
	}

	for _, tt := range tests {
		got := Label(tt.name)
		if got != tt.want {
			t.Errorf("Label(%q) = %q, want %q", tt.name, got, tt.want)
		}
	}
}

func TestFieldID(t *testing.T) {
	tests := []struct {
		name string
		want string
	}{
		{name: "email", want: "email"},
		{name: "post[title]", want: "post-title"},
		{name: " user email ", want: "user-email"},
		{name: "profile.avatar_url", want: "profile-avatar-url"},
		{name: "!!!", want: "field"},
	}

	for _, tt := range tests {
		got := FieldID(tt.name)
		if got != tt.want {
			t.Errorf("FieldID(%q) = %q, want %q", tt.name, got, tt.want)
		}
	}
}
`,
	"internal/views/assets/assets.go": `package assets

import (
	"net/url"
	"path"
	"strings"
)

const basePath = "/assets/"

func Path(name string) string {
	cleaned := path.Clean("/" + strings.TrimPrefix(name, "/"))
	if cleaned == "/" {
		return basePath
	}

	parts := strings.Split(strings.TrimPrefix(cleaned, "/"), "/")
	for i, part := range parts {
		parts[i] = url.PathEscape(part)
	}
	return basePath + strings.Join(parts, "/")
}
`,
	"internal/views/assets/assets_test.go": `package assets

import "testing"

func TestPathBuildsAssetURL(t *testing.T) {
	tests := []struct {
		name string
		want string
	}{
		{name: "", want: "/assets/"},
		{name: "app.css", want: "/assets/app.css"},
		{name: "/icons/logo.svg", want: "/assets/icons/logo.svg"},
		{name: "icons/../app.css", want: "/assets/app.css"},
		{name: "avatars/Jane Doe.png", want: "/assets/avatars/Jane%20Doe.png"},
	}

	for _, tt := range tests {
		got := Path(tt.name)
		if got != tt.want {
			t.Errorf("Path(%q) = %q, want %q", tt.name, got, tt.want)
		}
	}
}
`,
	"static/README.md": `# Static Assets

Place application static assets here.
`,
	"static/app.css": `body {
	margin: 2rem;
	font-family: system-ui, sans-serif;
}
`,
}
